language: python
python:
  - "3.6"    
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest queryprocessortest.py
deploy:
  provider: heroku
  api_key:
    secure: "LZtSY/M51zq1NOoLkWn/ArO5CMCGEVSANH+oxtQL/1IhxuDs1km9Qa51ZXM/qF/h0uyeU7NwneuyNyQ3fEISxAYNSyvpysPXSiT5feXexK79OFu6BPXx1mJvNTK9elYQvxOP+SIW4gTQNWQp47cE9H9Vcu3X8SZKKutMfgVDDJKWpIfsqjHThP6dZGb9L8pNriAF4ZujIK4UzjkRobqrp6mIdTollsIESjCXSpotd2xD4SdpLoRBq1isRIxIhvY6ttgXlK/SxWXzmWQx0J/dRnekmn7X7OBdRgbNCVFkn5guDbaot/c4sE0k8jfYS9uBfKPU8GprqnsPbKmVPo4/n0G9mF9BtAfn16gY0wZscTJXcEnDTb+5XNozNC8MSrcGTRfDaFBiXTy17/v9a/6mYfdENiA+/vxe1GiCxfoA6uZnsdt/KLWdGFrjSrppvvh8LUcZEJQ3KcBddynp6NJkW7riTvU79kldsdWrlXD3Mtf06w0NQ7SMykaECNWRMT9yWzTzCGdu/W4K10MUD/eW2rboLiRUnHgXfE6gSTne2PquIa87y6vywAw19i97WlbtmpqysMMiYIte76ZJk/x6Vn+iUIuI0HysoFHD9fycB/+upmvavlI9zVA41LY3a6lt+Qdka+q9iz6fQuR6AJjDBtZJVzjHX6jhkCfvDFF0rrM="
    app: intense-basin-73928